function normalizeFrac(n,d){const sign=d<0?-1:1;n*=sign;d*=sign;const g=gcd(n,d)||1;return [n/g,d/g]}function fracStr(n,d){[n,d]=normalizeFrac(n,d);return d===1?String(n):`${n}/${d}`}function parseFrac(v){v=String(v).trim().replace(/\s+/g,' ');if(/^[-+]?\d+(\.\d+)?$/.test(v))return Number(v);let m=v.match(/^(-?\d+)\s+(\d+)\/(\d+)$/);if(m)return Number(m[1])+(Number(m[1])<0?-1:1)*Number(m[2])/Number(m[3]);m=v.match(/^(-?\d+)\/(\d+)$/);if(m)return Number(m[1])/Number(m[2]);return NaN}function eqNum(a,b){return Math.abs(Number(a)-Number(b))<1e-6}function makeOptions(ans,kind='num'){if(typeof ans==='string'&&Number.isNaN(parseFrac(ans))&&kind!=='frac'){const m=ans.match(/^(\d+)x([+-]\d+)$/);let c=[ans];if(m){const a=Number(m[1]),b=Number(m[2]);c.push(`${a+1}x${b>=0?'+':''}${b}`,`${a}x${b+1>=0?'+':''}${b+1}`,`x${b>=0?'+':''}${b}`)}else c.push(ans+'1','1'+ans,ans.replace('+','−'));return shuffle([...new Set(c)]).slice(0,4)}let vals=[ans],guard=0;while(vals.length<4&&guard++<100){let v;if(kind==='frac'){const base=parseFrac(ans),delta=pick([.25,.5,1/3,-.25,-.5,1/6]);v=fracStr(Math.round((base+delta)*12),12)}else v=+(Number(ans)+pick([-10,-5,-2,-1,1,2,5,10])).toFixed(2);if(!vals.some(x=>String(x)===String(v)))vals.push(v)}return shuffle(vals)}
function Q(topic,type,prompt,answer,explanation,visual=''){if(type==='mixed')type=pick(['mc','input','tf']);return {topic,type,prompt,answer,explanation,visual}}
function genQuestion(id,requested='mixed',speed=false){let type=requested==='mixed'?pick(speed?['mc','input','tf']:['mc','input','tf']):requested;let q;
if(id==='rounding'){const p=pick([10,100,1000,10000]),n=R(1000,999999),a=Math.round(n/p)*p;if(type==='tf'){const shown=Math.random()<.5?a:a+p;q=Q(id,'tf',`${n.toLocaleString()} 四捨五入至最接近 ${p.toLocaleString()} 是 ${shown.toLocaleString()}。`,shown===a,`正確答案是 ${a.toLocaleString()}。`)}else q=Q(id,type,`${n.toLocaleString()} 四捨五入至最接近 ${p.toLocaleString()}：`,a,`望保留位右邊一格，再決定進一或不變。`)}
if(id==='fractionAdd'){let b=pick([2,3,4,5,6,8]),d=pick([3,4,5,6,8,10,12]);while(d===b)d=pick([3,4,5,6,8,10,12]);let a=R(1,b-1),c=R(1,d-1),op=Math.random()<.7?'+':'-';if(op==='-'&&a/b<c/d)[a,b,c,d]=[c,d,a,b];const m=lcm(b,d),N=a*(m/b)+(op==='+'?1:-1)*c*(m/d),ans=fracStr(N,m);if(type==='tf'){const fake=Math.random()<.5?ans:fracStr(N+1,m);q=Q(id,'tf',`${a}/${b} ${op} ${c}/${d} = ${fake}`,fake===ans,`通分至分母${m}，答案是${ans}。`)}else q=Q(id,type,`${a}/${b} ${op} ${c}/${d} = ?`,ans,`通分至${m}：${a*m/b}/${m} ${op} ${c*m/d}/${m} = ${ans}`)}
if(id==='fractionMul'){const b=pick([2,3,4,5,6]),d=pick([2,3,4,5,6]),a=R(1,b-1),c=R(1,d-1),ans=fracStr(a*c,b*d);q=Q(id,type==='tf'?'tf':type,`${a}/${b} × ${c}/${d} ${type==='tf'?'= '+(Math.random()<.5?ans:fracStr(a*c+1,b*d)):'= ?'}`,type==='tf'?undefined:ans,`分子乘分子、分母乘分母，再約分：${ans}`);if(type==='tf'){const shown=q.prompt.split('= ')[1],correct=shown===ans;q.answer=correct;q.explanation=`正確答案是${ans}。`}}
if(id==='fractionDiv'){const b=pick([2,3,4,5,6]),d=pick([2,3,4,5,6]),a=R(1,b-1),c=R(1,d-1),ans=fracStr(a*d,b*c);q=Q(id,type,`${a}/${b} ÷ ${c}/${d} = ?`,ans,`除以${c}/${d}等於乘${d}/${c}，答案${ans}。`)}
if(id==='decimal'){const a=R(12,99)/10,b=pick([.1,.5,1.2,1.5,2,3]),ans=+(a*b).toFixed(2);if(type==='tf'){const shown=Math.random()<.5?ans:+(ans*10).toFixed(2);q=Q(id,'tf',`${a} × ${b} = ${shown}`,shown===ans,`正確答案是${ans}。先估算可避免小數點錯位。`)}else q=Q(id,type,`${a} × ${b} = ?`,ans,`先當整數相乘，再放回小數點；答案${ans}。`)}
if(id==='operations'){const a=R(4,12),b=R(2,6),c=R(2,8),d=R(1,15);let prompt,ans;if(Math.random()<.45){prompt=`(${a}+${b}) × ${c} − ${d}`;ans=(a+b)*c-d}else{const product=a*b;prompt=`${product} ÷ ${b} × ${c} + ${d}`;ans=a*c+d}q=Q(id,type,prompt+' = ?',ans,'先括號，再乘除由左至右，最後加減由左至右。')}
if(id==='algebra'){const a=R(2,6),x=R(2,9),b=R(1,10),ans=a*x+b;if(type==='mc'&&Math.random()<.35){q=Q(id,'mc',`「一個數x的${a}倍再加${b}」應寫成：`,`${a}x+${b}`,'倍數表示乘法，所以是'+a+'x+'+b)}else q=Q(id,type,`當 x=${x}，${a}x+${b} = ?`,ans,`${a}×${x}+${b}=${ans}`)}
if(id==='equation'){const a=R(2,6),x=R(2,10),b=R(0,10),c=a*x+b;q=Q(id,type,`解方程：${a}x${b?`+${b}`:''}=${c}`,x,`${b?`兩邊先減${b}，`:''}再兩邊除${a}，x=${x}。`)}
if(id==='area'){const sh=pick(['三角形','平行四邊形','梯形']),base=R(4,14),h=R(3,10);let prompt,ans,ex;if(sh==='三角形'){ans=base*h/2;prompt=`三角形底${base}cm，高${h}cm，面積是？`;ex=`${base}×${h}÷2=${ans}cm²`}else if(sh==='平行四邊形'){ans=base*h;prompt=`平行四邊形底${base}cm，高${h}cm，面積是？`;ex=`${base}×${h}=${ans}cm²`}else{const top=R(2,base-1);ans=(top+base)*h/2;prompt=`梯形上底${top}cm，下底${base}cm，高${h}cm，面積是？`;ex=`(${top}+${base})×${h}÷2=${ans}cm²`}q=Q(id,type,prompt,ans,ex)}
if(id==='volume'){const l=R(2,8),w=R(2,6),h=R(2,5),ans=l*w*h;q=Q(id,type,`長方體長${l}cm、闊${w}cm、高${h}cm，體積是？`,ans,`${l}×${w}×${h}=${ans}cm³`)}
if(id==='circle'){const r=R(2,12),ask=Math.random()<.5?'d':'r';if(ask==='d')q=Q(id,type,`圓的半徑是${r}cm，直徑是？`,r*2,`直徑=半徑×2=${r*2}cm`);else q=Q(id,type,`圓的直徑是${r*2}cm，半徑是？`,r,`半徑=直徑÷2=${r}cm`)}
if(id==='solids'){const facts=[['正方體有6個面。',true,'正方體有6個面。'],['正方體有10條稜。',false,'正方體有12條稜。'],['球有頂點。',false,'球沒有頂點。'],['圓柱有兩個圓形底。',true,'圓柱有兩個相同的圓形底。'],['正方體有8個頂點。',true,'正方體有8個頂點。']];const f=pick(facts);if(type==='input'||type==='mc'){const sets=[['正方體有多少條稜？',12,'6面、12稜、8頂點。'],['正方體有多少個頂點？',8,'6面、12稜、8頂點。'],['正方體有多少個面？',6,'6面、12稜、8頂點。']];const x=pick(sets);q=Q(id,type,x[0],x[1],x[2])}else q=Q(id,'tf',f[0],f[1],f[2])}
if(id==='chart'){const boys=R(5,15),girls=R(5,15),ask=pick(['difference','total']);const ans=ask==='difference'?Math.abs(boys-girls):boys+girls;const visual=`<div style="width:min(500px,100%)"><b>足球喜好人數</b><div style="height:22px;width:${boys*5}%;max-width:100%;background:#60a5fa;border-radius:8px;margin:8px 0"></div><div>男生 ${boys}</div><div style="height:22px;width:${girls*5}%;max-width:100%;background:#d8b4fe;border-radius:8px;margin:8px 0"></div><div>女生 ${girls}</div></div>`;q=Q(id,type,ask==='difference'?'男生和女生相差多少人？':'男生和女生共有多少人？',ans,ask==='difference'?`|${boys}-${girls}|=${ans}`:`${boys}+${girls}=${ans}`,visual)}
if(id==='word'){const kind=pick(['unit','fraction','money']);if(kind==='unit'){const per=R(4,9),q1=R(3,6),q2=R(7,12),total=per*q1,ans=per*q2;q=Q(id,type,`${q1}本簿共$${total}，${q2}本簿共多少元？`,ans,`先求1本：${total}÷${q1}=${per}；再求${q2}本：${per}×${q2}=${ans}。`)}else if(kind==='fraction'){const total=pick([24,30,36,40,48]),den=pick([3,4,5,6]),num=R(1,den-1),ans=total*num/den;q=Q(id,type,`一盒有${total}粒糖，吃了${num}/${den}，吃了多少粒？`,ans,`${total}÷${den}×${num}=${ans}粒。`)}else{const price=R(8,25),pay=pick([50,100]),qty=R(2,4),cost=price*qty;if(cost>=pay)return genQuestion(id,requested,speed);q=Q(id,type,`每件$${price}，買${qty}件，用$${pay}付款，找回多少元？`,pay-cost,`${price}×${qty}=${cost}，${pay}-${cost}=${pay-cost}。`)}}
if(!q)return genQuestion('operations',requested,speed);if(type==='tf'&&typeof q.answer!=='boolean'){const real=q.answer,isTrue=Math.random()<.5,kind=typeof real==='string'&&real.includes('/')?'frac':'num',fake=makeOptions(real,kind).find(x=>String(x)!==String(real))??(Number(real)+1),shown=isTrue?real:fake;q.prompt=q.prompt.replace(/\s*[?？]\s*$/,'').replace(/=\s*$/,'')+`；答案是 ${shown}。`;q.answer=isTrue;q.explanation+=` 正確答案是${real}。`}if(q.type==='mc'){q.options=makeOptions(q.answer,typeof q.answer==='string'&&q.answer.includes('/')?'frac':'num')}return q}

function selectMode(mode){state.mode=mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));$('topicField').classList.toggle('hide',mode==='mixed'||mode==='speed'||mode==='wrong'||mode==='teacher');$('lengthField').classList.toggle('hide',mode==='speed'||mode==='teacher');$('qType').disabled=mode==='teacher';$('qType').value=mode==='teacher'?'mixed':$('qType').value;$('startBtn').textContent=mode==='speed'?'開始60秒':mode==='wrong'?'開始重溫':'開始'}document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>selectMode(b.dataset.mode));
function buildTopicSelect(){$('practiceTopic').innerHTML=topicIds.map(id=>`<option value="${id}">${topicMeta[id].icon} ${topicMeta[id].title}</option>`).join('')}
function startPractice(){clearInterval(state.timer);$('quiz').classList.add('show');$('play').classList.remove('hide');$('result').classList.remove('show');state.index=0;state.score=0;state.answered=false;state.answeredCount=0;state.topicStats={};const req=$('qType').value;let len=Number($('qLength').value);if(state.mode==='teacher')len=10;if(state.mode==='wrong'){const wrong=store.get('p5v2_wrong')||[];if(!wrong.length){alert('暫時未有錯題。先完成其他練習吧！');return}state.questions=shuffle(wrong).slice(0,len).map(x=>({...x,options:undefined}));state.questions=state.questions.map(q=>q.type==='mc'?({...q,options:makeOptions(q.answer,typeof q.answer==='string'&&q.answer.includes('/')?'frac':'num')}):q)}else if(state.mode==='unit'){const id=$('practiceTopic').value;state.questions=Array.from({length:len},()=>genQuestion(id,req))}else if(state.mode==='speed'){state.timeLeft=60;state.questions=Array.from({length:60},()=>genQuestion(pick(['rounding','decimal','operations','algebra','equation','circle']),req,true));state.timer=setInterval(()=>{state.timeLeft--;$('count').textContent=`剩餘 ${state.timeLeft} 秒`;if(state.timeLeft<=0)finishPractice()},1000)}else{const pool=state.mode==='teacher'?topicIds:topicIds;state.questions=Array.from({length:len},(_,i)=>genQuestion(pool[i%pool.length]||pick(pool),req))}showQuestion();jump('quiz')}
function showQuestion(){state.answered=false;$('feedback').className='feedback';$('feedback').innerHTML='';$('nextBtn').style.display='none';const q=state.questions[state.index];if(!q){finishPractice();return}$('qTopic').textContent=`${topicMeta[q.topic].icon} ${topicMeta[q.topic].title}`;$('question').textContent=q.prompt;$('qVisual').innerHTML=q.visual||'';$('timerScore').textContent=`${state.score}分`;if(state.mode!=='speed')$('count').textContent=`第 ${state.index+1} / ${state.questions.length} 題`;$('progressIn').style.width=(state.mode==='speed'?Math.min(100,(60-state.timeLeft)/60*100):(state.index/state.questions.length*100))+'%';let html='';if(q.type==='mc')html=`<div class="choices">${q.options.map((o,i)=>`<button class="choice" onclick="answerMC(${i},this)">${o}</button>`).join('')}</div>`;else if(q.type==='tf')html=`<div class="choices tf"><button class="choice" onclick="answerTF(true,this)">✓ 正確</button><button class="choice" onclick="answerTF(false,this)">✗ 錯誤</button></div>`;else html=`<div class="inputRow"><input id="userAnswer" class="answerInput" inputmode="decimal" placeholder="輸入答案；分數可寫 5/6"><button class="btn dark" onclick="answerInput()">提交</button></div>`;$('answerArea').innerHTML=html;if(q.type==='input')setTimeout(()=>$('userAnswer')?.focus(),80)}
function isCorrect(q,val){if(typeof q.answer==='boolean')return val===q.answer;if(typeof q.answer==='number')return eqNum(parseFrac(val),q.answer);return eqNum(parseFrac(val),parseFrac(q.answer))||String(val).trim()===String(q.answer)}
function answerMC(i,btn){if(state.answered)return;const q=state.questions[state.index];document.querySelectorAll('.choice').forEach((b,j)=>{if(String(q.options[j])===String(q.answer))b.classList.add('correct')});if(String(q.options[i])!==String(q.answer))btn.classList.add('wrong');recordAnswer(q,String(q.options[i])===String(q.answer))}function answerTF(v,btn){if(state.answered)return;const q=state.questions[state.index];document.querySelectorAll('.choice').forEach((b,i)=>{const val=i===0;if(val===q.answer)b.classList.add('correct')});if(v!==q.answer)btn.classList.add('wrong');recordAnswer(q,v===q.answer)}function answerInput(){if(state.answered)return;const q=state.questions[state.index],v=$('userAnswer').value.trim();if(!v)return;recordAnswer(q,isCorrect(q,v))}
function recordAnswer(q,ok){state.answered=true;state.answeredCount++;const p=store.get('p5v2_progress')||{attempt:0,correct:0,best:0};p.attempt++;if(ok){p.correct++;state.score++}store.set('p5v2_progress',p);state.topicStats[q.topic]=state.topicStats[q.topic]||{a:0,c:0};state.topicStats[q.topic].a++;if(ok)state.topicStats[q.topic].c++;let wrong=store.get('p5v2_wrong')||[];if(!ok){wrong.unshift({topic:q.topic,type:q.type,prompt:q.prompt,answer:q.answer,explanation:q.explanation,visual:q.visual||''});wrong=wrong.filter((x,i,a)=>a.findIndex(y=>y.topic===x.topic&&y.prompt===x.prompt)===i).slice(0,30)}else wrong=wrong.filter(x=>!(x.topic===q.topic&&x.prompt===q.prompt));store.set('p5v2_wrong',wrong);$('feedback').className=`feedback show ${ok?'ok':'no'}`;$('feedback').innerHTML=`<strong>${ok?'✅ 答啱！':'❌ 未啱。'}</strong><br>${q.explanation}<br><small>正確答案：${typeof q.answer==='boolean'?(q.answer?'正確':'錯誤'):q.answer}</small>`;$('timerScore').textContent=`${state.score}分`;updateStats();if(state.mode==='speed'){setTimeout(()=>{if(state.timer){state.index++;showQuestion()}},650)}else $('nextBtn').style.display='inline-block'}function nextQuestion(){state.index++;if(state.index>=state.questions.length)finishPractice();else showQuestion()}
function finishPractice(){clearInterval(state.timer);state.timer=null;$('play').classList.add('hide');$('result').classList.add('show');const total=state.mode==='speed'?state.answeredCount:state.questions.length,score=state.score;$('score').textContent=`${score}/${total}`;let msg=total?Math.round(score/total*100):0;$('resultMsg').textContent=msg>=90?'非常好！可以挑戰混合題。':msg>=70?'掌握得唔錯，重溫錯題會更穩。':'先返去視覺課程重溫，再做一次。';if(state.mode==='mixed'||state.mode==='teacher'){const p=store.get('p5v2_progress')||{attempt:0,correct:0,best:0};p.best=Math.max(p.best,total?Math.round(score/total*10):0);store.set('p5v2_progress',p)}const rows=Object.entries(state.topicStats).map(([id,x])=>`<div style="display:flex;justify-content:space-between;border-bottom:1px solid #e5e7eb;padding:7px"><span>${topicMeta[id].icon} ${topicMeta[id].title}</span><b>${x.c}/${x.a}</b></div>`).join('');$('analysis').innerHTML=rows?`<div class="panel" style="text-align:left;margin:15px auto;max-width:620px"><h3>課題分析</h3>${rows}</div>`:'';updateStats()}
function updateStats(){const seen=store.get('p5v2_seen')||[],p=store.get('p5v2_progress')||{attempt:0,correct:0,best:0},wrong=store.get('p5v2_wrong')||[];$('sSeen').textContent=seen.length;$('sAttempt').textContent=p.attempt;$('sRate').textContent=p.attempt?Math.round(p.correct/p.attempt*100)+'%':'0%';$('sBest').textContent=(p.best||0)+'/10';$('sWrong').textContent=wrong.length;$('wrongList').innerHTML=wrong.slice(0,5).map(x=>`<div class="wrongItem"><span class="pill">${topicMeta[x.topic].title}</span><div style="font-weight:900;margin-top:6px">${x.prompt}</div><small style="color:#64748b">答案：${typeof x.answer==='boolean'?(x.answer?'正確':'錯誤'):x.answer}</small></div>`).join('')||'<div style="color:#64748b">暫時未有錯題。</div>'}
function resetProgress(){if(!confirm('確定清除所有學習紀錄？'))return;['p5v2_seen','p5v2_progress','p5v2_wrong'].forEach(k=>{try{localStorage.removeItem(k)}catch(e){}});updateStats()}
renderTabs();renderTopics();buildTopicSelect();selectMode('unit');updateStats();