const $=id=>document.getElementById(id), R=(a,b)=>Math.floor(Math.random()*(b-a+1))+a, pick=a=>a[R(0,a.length-1)], gcd=(a,b)=>b?gcd(b,a%b):Math.abs(a), lcm=(a,b)=>Math.abs(a*b)/gcd(a,b), shuffle=a=>[...a].sort(()=>Math.random()-.5), clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const mem={};const store={get(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch(e){return mem[k]??null}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){mem[k]=v}}};
let state={mode:'unit',questions:[],index:0,score:0,answered:false,answeredCount:0,currentTopic:'rounding',timer:null,timeLeft:60,topicStats:{}};
const categories=['全部','數與運算','代數','度量','圖形與空間','數據處理','應用題'];
const topicMeta={
rounding:{icon:'🔢',cat:'數與運算',title:'多位數與四捨五入',desc:'位值、比較大數、四捨五入及估算。',objectives:['讀寫及比較多位數','四捨五入至千、萬、十萬或更高位','用估算檢查答案是否合理'],tip:'先叫學生用手指遮住保留位右邊，再只望下一格。唔好一次過望晒所有數字。'},
fractionAdd:{icon:'🍕',cat:'數與運算',title:'異分母分數加減',desc:'通分、最簡分數、帶分數與最多三項運算。',objectives:['找分母的最小公倍數','把分數通分後才加減分子','答案化成最簡分數或帶分數'],tip:'用同樣大小的紙條或薄餅解釋：切法唔同，件數不能直接相加。'},
fractionMul:{icon:'✖️',cat:'數與運算',title:'分數乘法',desc:'分數乘整數、分數乘分數及約分。',objectives:['理解「一個數的幾分之幾」','分子乘分子、分母乘分母','計算前或計算後約分'],tip:'將「2/3 × 3/5」讀成「3/5入面的2/3」，用重疊方格展示交集。'},
fractionDiv:{icon:'➗',cat:'數與運算',title:'分數除法',desc:'分數除法、倒數及乘除混合運算。',objectives:['理解除法是分組或量度','除以分數等於乘其倒數','答案約分及判斷大小'],tip:'先問「3/4入面有幾多個1/4？」建立分組概念，再教乘倒數規則。'},
decimal:{icon:'💧',cat:'數與運算',title:'小數乘法',desc:'乘10、100、0.1，以及小數乘小數。',objectives:['理解小數位值移動','先估算答案大小','正確放回小數點'],tip:'先估算，例如2.4×1.5約等於3，最後答案如果係36就立即知道小數點錯。'},
operations:{icon:'🚦',cat:'數與運算',title:'四則混合運算',desc:'括號、乘除、加減及同級由左至右。',objectives:['先算括號','乘除同級由左至右','加減同級由左至右'],tip:'唔好教「一定先乘後除」。正確係乘除同級，由左至右。'},
algebra:{icon:'🧩',cat:'代數',title:'初步代數',desc:'用字母表示未知數、代入求值及列代數式。',objectives:['明白x代表一個數','3x代表3×x','把文字敘述寫成代數式'],tip:'用盒子代表未知數：3個盒就是3x；盒子加5粒糖就是x+5。'},
equation:{icon:'⚖️',cat:'代數',title:'簡易方程',desc:'x+b=c、ax=b及ax+b=c。',objectives:['用天平理解等號','兩邊做相同運算','代入驗算答案'],tip:'每一步都問學生：「左邊做咗乜？右邊要做乜？」避免只背「移項變號」。'},
area:{icon:'📐',cat:'度量',title:'三角形、平行四邊形與梯形面積',desc:'辨認底和垂直高，計算基本及複合圖形。',objectives:['分辨高與斜邊','使用正確面積公式','單位寫平方厘米cm²'],tip:'用剪拼法：三角形兩個拼成平行四邊形，所以除2；梯形兩個拼成平行四邊形。'},
volume:{icon:'🧊',cat:'度量',title:'長方體與正方體體積',desc:'數立方單位、每層數量及簡單組合立體。',objectives:['理解體積是佔用空間','長×闊先求每層','再乘高／層數，單位cm³'],tip:'先問一層幾多粒，再問有幾多層，學生通常會自然得出長×闊×高。'},
circle:{icon:'⭕',cat:'圖形與空間',title:'圓',desc:'圓心、半徑、直徑、圓周及使用圓規。',objectives:['辨認圓心、半徑、直徑','直徑=2×半徑','半徑=直徑÷2'],tip:'提醒直徑一定經過圓心；任何由圓心到圓周的線段都是半徑。'},
solids:{icon:'🎲',cat:'圖形與空間',title:'立體圖形與展開圖',desc:'面、稜、頂點、截面及正方體／長方體／圓柱展開圖。',objectives:['數出面、稜和頂點','辨認常見展開圖','判斷平行切面形狀'],tip:'可用紙盒實物，叫學生摸住面、沿住稜行、指住頂點，避免只背數字。'},
chart:{icon:'📊',cat:'數據處理',title:'複合棒形圖',desc:'閱讀兩組數據、比較、總和、相差及選擇刻度。',objectives:['讀取橫向或縱向複合棒形圖','比較兩組數據','選擇合適刻度並作圖'],tip:'先睇圖例，再睇刻度，最後先睇棒的高度。好多錯誤係未睇清每格代表幾多。'},
word:{icon:'🧠',cat:'應用題',title:'文字題與數學建模',desc:'圈資料、選運算、列式、檢查答案及寫答句。',objectives:['找已知與未知','畫線段圖或表格','估算及解釋答案是否合理'],tip:'固定五步：讀、圈、畫、式、查。叫學生用一句話講「我而家要先求乜」。'}
};
const topicIds=Object.keys(topicMeta);
function jump(id){$(id).scrollIntoView({behavior:'smooth',block:'start'})}function navTo(id,b){document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');jump(id)}
$('teacherBtn').onclick=()=>{document.body.classList.toggle('teach');$('teacherBtn').classList.toggle('on');};
function renderTabs(){ $('catTabs').innerHTML=categories.map((c,i)=>`<button class="cat ${i===0?'active':''}" onclick="filterTopics('${c}',this)">${c}</button>`).join('');}
function filterTopics(cat,btn){document.querySelectorAll('.cat').forEach(x=>x.classList.remove('active'));btn.classList.add('active');renderTopics(cat)}
function renderTopics(cat='全部'){const ids=topicIds.filter(id=>cat==='全部'||topicMeta[id].cat===cat);$('topicCount').textContent=`${ids.length} 個課題`;$('topicGrid').innerHTML=ids.map(id=>{const t=topicMeta[id];const colors={數與運算:['#dbeafe','#1d4ed8'],代數:['#ede9fe','#6d28d9'],度量:['#dcfce7','#15803d'],'圖形與空間':['#ffedd5','#c2410c'],數據處理:['#fef3c7','#a16207'],應用題:['#fee2e2','#b91c1c']}[t.cat];return `<article class="topic"><div class="topicIcon" style="background:${colors[0]};color:${colors[1]}">${t.icon}</div><span class="tag" style="background:${colors[0]};color:${colors[1]}">${t.cat}</span><h3>${t.title}</h3><p>${t.desc}</p><button onclick="openCourse('${id}')">視覺教學 →</button></article>`}).join('')}
function step(n,txt){return `<div class="step"><div class="num">${n}</div><div>${txt}</div></div>`}function fracBar(n,d,cls){return `<div class="fractionBar">${Array.from({length:d},(_,i)=>`<div class="fcell ${i<n?cls:''}"></div>`).join('')}</div>`}
function markSeen(id){const s=new Set(store.get('p5v2_seen')||[]);s.add(id);store.set('p5v2_seen',[...s]);updateStats()}
function openCourse(id){state.currentTopic=id;markSeen(id);const t=topicMeta[id];$('courseCategory').textContent=t.cat;$('courseTitle').textContent=`${t.icon} ${t.title}`;$('teacherNote').innerHTML=`<strong>教師說法：</strong>${t.tip}`;$('courseObjectives').innerHTML='<ul style="margin:0;padding-left:22px">'+t.objectives.map(x=>`<li>${x}</li>`).join('')+'</ul>';$('coursePanel').classList.add('show');renderDemo(id);setTimeout(()=>$('coursePanel').scrollIntoView({behavior:'smooth',block:'start'}),40)}function closeCourse(){$('coursePanel').classList.remove('show')}function newDemo(){renderDemo(state.currentTopic)}function practiceCurrent(){state.mode='unit';selectMode('unit');$('practiceTopic').value=state.currentTopic;jump('practice');setTimeout(startPractice,250)}
function renderDemo(id){const V=$('courseVisual'),S=$('courseSteps');let h='',s='';
if(id==='rounding'){const p=pick([1000,10000,100000]),n=R(100000,999999),a=Math.round(n/p)*p,raw=String(n),idx=raw.length-1-Math.log10(p),right=Number(raw[idx+1]);h=`<div><div class="placeRow">${raw.split('').map((d,i)=>`<div class="placeBox ${i===idx?'hot':''}">${d}<small>${['十萬','萬','千','百','十','個'][i]}</small></div>`).join('')}</div><div class="formula">${n.toLocaleString()} ≈ ${a.toLocaleString()}</div></div>`;s=step(1,`保留<strong>${p.toLocaleString()}位</strong>。`)+step(2,`望右邊一格：<strong>${right}</strong>。`)+step(3,right>=5?'5或以上，向上進一。':'少於5，保留位不變。')}
if(id==='fractionAdd'){let b=pick([2,3,4,5,6]),d=pick([3,4,5,6,8]);while(d===b)d=pick([3,4,5,6,8]);const a=R(1,b-1),c=R(1,d-1),m=lcm(b,d),A=a*m/b,C=c*m/d,N=A+C,g=gcd(N,m);h=`<div style="width:min(650px,100%);display:grid;gap:12px"><b class="formula">${a}/${b} ＋ ${c}/${d}</b>${fracBar(a,b,'fillA')}${fracBar(c,d,'fillB')}<div class="formula">＝ ${A}/${m} ＋ ${C}/${m} ＝ ${N/g}/${m/g}</div></div>`;s=step(1,`找${b}和${d}的最小公倍數：<strong>${m}</strong>。`)+step(2,`通分：${a}/${b}=${A}/${m}，${c}/${d}=${C}/${m}。`)+step(3,`分母不變，分子相加，再約分。`)}
if(id==='fractionMul'){const a=2,b=3,c=3,d=5;h=`<div><div class="formula">2/3 × 3/5</div><div class="grid15">${Array.from({length:15},(_,i)=>{const row=Math.floor(i/5),col=i%5;const x=row<2,y=col<3;return `<span class="${x&&y?'overlap':x?'shadeX':y?'shadeY':''}"></span>`}).join('')}</div><div class="formula">重疊 6 格 ÷ 全部 15 格 = 2/5</div></div>`;s=step(1,'把整體分成3×5＝15格。')+step(2,'先塗3/5，再取其中的2/3。')+step(3,'重疊部分是6/15，約分成2/5。')}
if(id==='fractionDiv'){h=`<div style="width:min(650px,100%);display:grid;gap:12px"><div class="formula">3/4 ÷ 1/4</div>${fracBar(3,4,'fillA')}<div style="display:flex;justify-content:space-around;font-weight:950"><span>1/4</span><span>1/4</span><span>1/4</span><span style="opacity:.25">1/4</span></div><div class="formula">3/4 入面有 3 個 1/4</div></div>`;s=step(1,'除法可以理解成「入面有幾多組」。')+step(2,'3/4可以分成3組1/4。')+step(3,'所以3/4 ÷ 1/4 = 3。')}
if(id==='decimal'){const a=pick([1.2,2.4,3.5,4.8]),b=pick([0.5,1.5,2.2]),ans=+(a*b).toFixed(2);h=`<div><div class="placeRow"><div class="placeBox">${String(a).split('.')[0]}<small>個位</small></div><div class="placeBox hot">${String(a).split('.')[1]}<small>十分位</small></div></div><div class="formula">${a} × ${b} = ${ans}</div></div>`;const dec=(String(a).split('.')[1]?.length||0)+(String(b).split('.')[1]?.length||0);s=step(1,`先估算：答案大約是${Math.round(a)}×${Math.round(b)}。`)+step(2,'暫時當整數相乘。')+step(3,`兩個乘數合共有${dec}個小數位，答案由右起數${dec}位放小數點。`)}
if(id==='operations'){h=`<div style="text-align:center"><div style="font-size:55px">🟣 → 🔵 → 🟢</div><div class="formula">(括號) → × ÷ → ＋ −</div><div class="formula">48 ÷ 6 × 7 ＋ 15 = 71</div></div>`;s=step(1,'先做括號。')+step(2,'乘法和除法同級，從左至右。')+step(3,'加法和減法同級，從左至右。')+step(4,'48÷6=8，8×7=56，56+15=71。')}
if(id==='algebra'){const x=R(2,8),a=R(2,4),b=R(1,8);h=`<div><div class="tiles">${Array.from({length:a},()=>'<div class="tile">x</div>').join('')}<div class="tile const">＋ ${b}</div></div><div class="formula">${a}x＋${b}，當 x=${x}</div><div class="formula">=${a}×${x}＋${b}=${a*x+b}</div></div>`;s=step(1,'x是一個未知或可改變的數。')+step(2,`${a}x代表${a}×x，不是${a}＋x。`)+step(3,`把x換成${x}再計算。`)}
if(id==='equation'){const a=R(2,4),x=R(2,7),b=R(1,8),c=a*x+b;h=`<div class="balance"><div class="pans"><div class="pan">${Array.from({length:a},()=>'<span class="tile">x</span>').join('')}<span class="tile const">+${b}</span></div><div class="pan"><span class="tile const">${c}</span></div></div><div class="beam"></div><div class="formula">${a}x＋${b}＝${c}</div></div>`;s=step(1,`兩邊同時減${b}：${a}x=${c-b}。`)+step(2,`兩邊同時除${a}：x=${x}。`)+step(3,`驗算：${a}×${x}+${b}=${c}。`)}
if(id==='area'){const type=pick(['triangle','parallelogram','trapezium']),base=R(6,12),height=R(3,8),top=R(2,base-2);if(type==='triangle'){h=`<svg class="shapeSvg" viewBox="0 0 520 260"><polygon points="70,220 450,220 210,45" fill="#bfdbfe" stroke="#1d4ed8" stroke-width="5"/><line x1="210" y1="45" x2="210" y2="220" stroke="#dc2626" stroke-width="4" stroke-dasharray="8 7"/><text x="235" y="135" font-size="22" font-weight="900">高 ${height}</text><text x="225" y="250" font-size="22" font-weight="900">底 ${base}</text></svg><div class="formula">${base}×${height}÷2=${base*height/2} cm²</div>`;s=step(1,'找底和與底垂直的高。')+step(2,'底×高。')+step(3,'三角形是相同底高平行四邊形的一半，所以÷2。')}else if(type==='parallelogram'){h=`<svg class="shapeSvg" viewBox="0 0 520 260"><polygon points="130,45 440,45 370,220 60,220" fill="#dcfce7" stroke="#15803d" stroke-width="5"/><line x1="130" y1="45" x2="130" y2="220" stroke="#dc2626" stroke-width="4" stroke-dasharray="8 7"/><text x="150" y="135" font-size="22" font-weight="900">高 ${height}</text><text x="195" y="250" font-size="22" font-weight="900">底 ${base}</text></svg><div class="formula">${base}×${height}=${base*height} cm²</div>`;s=step(1,'斜邊不是高。高要與底垂直。')+step(2,'平行四邊形面積=底×高。')}else{const ans=(top+base)*height/2;h=`<svg class="shapeSvg" viewBox="0 0 520 260"><polygon points="150,45 350,45 440,220 60,220" fill="#ffedd5" stroke="#c2410c" stroke-width="5"/><line x1="150" y1="45" x2="150" y2="220" stroke="#dc2626" stroke-width="4" stroke-dasharray="8 7"/><text x="215" y="38" font-size="21" font-weight="900">上底 ${top}</text><text x="205" y="250" font-size="21" font-weight="900">下底 ${base}</text><text x="165" y="135" font-size="21" font-weight="900">高 ${height}</text></svg><div class="formula">(${top}+${base})×${height}÷2=${ans} cm²</div>`;s=step(1,'先加兩條平行邊：上底+下底。')+step(2,'乘高。')+step(3,'最後除2。')}}
if(id==='volume'){const l=R(3,6),w=R(2,4),hh=R(2,4),total=l*w*hh;h=`<div><div class="tiles" style="max-width:420px">${Array.from({length:Math.min(total,36)},()=>'<div class="miniCube"></div>').join('')}</div><div class="formula">長${l} × 闊${w} × 高${hh} = ${total} cm³</div></div>`;s=step(1,`一層有${l}×${w}=${l*w}粒。`)+step(2,`一共有${hh}層。`)+step(3,`${l*w}×${hh}=${total}立方厘米。`)}
if(id==='circle'){const r=R(3,8);h=`<svg class="shapeSvg" viewBox="0 0 420 280"><circle cx="210" cy="135" r="100" fill="#dbeafe" stroke="#1d4ed8" stroke-width="5"/><circle cx="210" cy="135" r="6" fill="#dc2626"/><line x1="210" y1="135" x2="310" y2="135" stroke="#16a34a" stroke-width="5"/><line x1="110" y1="160" x2="310" y2="160" stroke="#7c3aed" stroke-width="5"/><text x="235" y="125" font-size="20" font-weight="900">半徑 ${r}</text><text x="170" y="190" font-size="20" font-weight="900">直徑 ${r*2}</text></svg>`;s=step(1,'圓心到圓周是半徑。')+step(2,'經過圓心、兩端在圓周的是直徑。')+step(3,`直徑=${r}×2=${r*2}。`)}
if(id==='solids'){h=`<div style="display:grid;grid-template-columns:repeat(2,1fr);gap:12px;width:min(580px,100%)"><div class="panel" style="text-align:center"><div style="font-size:55px">🎲</div><b>正方體</b><div>6面・12稜・8頂點</div></div><div class="panel" style="text-align:center"><div style="font-size:55px">🥫</div><b>圓柱</b><div>2個圓形底＋1個曲面</div></div><div class="panel" style="text-align:center"><div style="font-size:55px">🔺</div><b>角錐</b><div>頂部收成一個頂點</div></div><div class="panel" style="text-align:center"><div style="font-size:55px">⚽</div><b>球</b><div>沒有稜和頂點</div></div></div>`;s=step(1,'面：平面或曲面。')+step(2,'稜：兩個面相交的邊。')+step(3,'頂點：多條稜相遇的點。')}
if(id==='chart'){const a=[R(4,10),R(4,10),R(4,10)],b=[R(4,10),R(4,10),R(4,10)],names=['足球','游泳','籃球'];h=`<div class="chartWrap"><div style="display:flex;gap:14px;justify-content:center;font-weight:900"><span style="color:#2563eb">■ 男生</span><span style="color:#c026d3">■ 女生</span></div>${names.map((n,i)=>`<div style="display:grid;grid-template-columns:50px 1fr;gap:8px;align-items:center;margin:12px 0"><b>${n}</b><div><div style="width:${a[i]*8}%;max-width:100%;height:18px;background:#60a5fa;border-radius:8px;margin-bottom:4px"></div><div style="width:${b[i]*8}%;max-width:100%;height:18px;background:#d8b4fe;border-radius:8px"></div><small>男${a[i]}　女${b[i]}</small></div></div>`).join('')}</div>`;s=step(1,'先看圖例，知道每種顏色代表誰。')+step(2,'再看刻度或數字。')+step(3,'最後比較、相加或相減。')}
if(id==='word'){const price=R(4,9),qty=R(3,6),want=R(7,12);h=`<div style="width:min(620px,100%)"><div class="formula">${qty}本簿共 $${price*qty}，${want}本幾多錢？</div><div style="display:flex;border:3px solid #334155;border-radius:10px;overflow:hidden;margin:14px 0">${Array.from({length:qty},()=>`<div style="flex:1;padding:15px;background:#bfdbfe;border-right:2px solid #64748b;text-align:center;font-weight:950">$${price}</div>`).join('')}</div><div class="formula">先求1本，再求${want}本</div></div>`;s=step(1,`讀：已知${qty}本共$${price*qty}。`)+step(2,`先求1本：${price*qty}÷${qty}=$${price}。`)+step(3,`再求${want}本：${price}×${want}=$${price*want}。`)+step(4,'查：本數增加，總價亦應增加。')}
V.innerHTML=h;S.innerHTML=s}